@hostname = localhost
@port = 8080
@baseUrl = http://{{hostname}}:{{port}}
@contentType = application/json


### ゲーム情報
#### 一覧
@query_gameInfos = {gameInfos{gameId%20state%20startTime%20endTime}}
GET {{baseUrl}}/graphql?query={{query_gameInfos}}

#### 単体
@query_gameInfo = {gameInfo(id:3s){gameId%20state%20progresses{piecies%20time}}}
GET {{baseUrl}}/graphql?query={{query_gameInfo}}

#### 追加
POST {{baseUrl}}/graphql?
content-type: application/json

{
  "query" : "mutation {createGameInfo(state: 2) {    gameId, state  }}"
}


### ゲーム進捗
#### 一覧
@query_progresses = {pregresses(id:2){gameId%20piecies%20time}}
GET {{baseUrl}}/graphql?query={{query_progresses}}


### ゲーム進捗単体
@query_progress = {progressLast(id:2){gameId}}
GET {{baseUrl}}/graphql?query={{query_progress}}

