@hostname = localhost
@port = 8080
@baseUrl = http://{{hostname}}:{{port}}
@contentType = application/json


### ゲーム情報
@query_gameInfos = {gameInfos{gameId%20state}}
GET {{baseUrl}}/graphql?query={{query_gameInfos}}


### ゲーム情報
@query_gameInfo = {gameInfo(id:2){gameId%20state}}
GET {{baseUrl}}/graphql?query={{query_gameInfo}}


